import mermaid from 'mermaid';

mermaid.initialize({
  startOnLoad: false,
  securityLevel: 'strict',
  theme: 'base',
  themeVariables: {
    background: 'transparent',
    primaryColor: '#dbeafe',
    primaryTextColor: '#172033',
    primaryBorderColor: '#2563eb',
    secondaryColor: '#dcfce7',
    secondaryTextColor: '#172033',
    secondaryBorderColor: '#16a34a',
    tertiaryColor: '#fef3c7',
    tertiaryTextColor: '#172033',
    tertiaryBorderColor: '#d97706',
    mainBkg: '#dbeafe',
    secondBkg: '#dcfce7',
    nodeBorder: '#2563eb',
    clusterBkg: '#f8fafc',
    clusterBorder: '#94a3b8',
    lineColor: '#64748b',
    edgeLabelBackground: '#f8fafc',
    textColor: '#172033',
    titleColor: '#172033',
    actorBkg: '#dbeafe',
    actorBorder: '#2563eb',
    actorTextColor: '#172033',
    actorLineColor: '#64748b',
    signalColor: '#64748b',
    signalTextColor: '#172033',
    noteBkgColor: '#fef3c7',
    noteTextColor: '#172033',
    noteBorderColor: '#d97706',
    labelBoxBkgColor: '#f8fafc',
    labelBoxBorderColor: '#94a3b8',
    labelTextColor: '#172033',
    loopTextColor: '#172033',
    stateBkg: '#dbeafe',
    stateBorder: '#2563eb',
    classText: '#172033',
    taskBkgColor: '#dbeafe',
    taskTextColor: '#172033',
    taskTextOutsideColor: '#172033',
    taskBorderColor: '#2563eb',
    activeTaskBkgColor: '#fef3c7',
    doneTaskBkgColor: '#dcfce7',
    critBkgColor: '#fee2e2',
    sectionBkgColor: '#dbeafe',
    sectionBkgColor2: '#dcfce7',
    gridColor: '#cbd5e1'
  }
});

window.__richdownMermaid = mermaid;
